#include "drivers/audio/audio_i2s.h"
#include "drivers/audio/audio_i2s_pio.h"
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "hardware/irq.h"
#include "hardware/clocks.h"
#include "hardware/gpio.h"

// ── Pin / PIO assignments ─────────────────────────────────────────────────────
// PA_CTRL: power amplifier enable (active HIGH)
#define PA_CTRL_PIN  19
// I2S data output to ES8311 DAC input
#define DOUT_PIN     20
// MCLK output to ES8311 (must be running before ES8311 can generate BCLK/LRCLK)
#define MCLK_PIN     22
// LRCLK (GPIO 23) and BCLK (GPIO 24) are generated by ES8311 in master mode.
// Their numbers are hardcoded in the PIO bytecodes in audio_i2s_pio.h.
#define LRCLK_PIN    23  // input from ES8311

#define MCLK_PIO      pio1
#define MCLK_PIO_SM   0
#define DOUT_PIO      pio2
#define DOUT_PIO_SM   0

// MCLK = 32000 * 192 = 6144000 Hz.  PIO generates via 5-instruction loop.
// div = sys_clk / (mclk_hz * 5)  = 150000000 / 30720000 = 4.8828125
#define AUDIO_MCLK_HZ  (AUDIO_I2S_SAMPLE_RATE * 192u)

// ── DMA state ─────────────────────────────────────────────────────────────────
// Two buffers — one playing, one being filled by the callback.
// FatFS uses DMA_IRQ_1; audio uses DMA_IRQ_0 (same split as audio_pwm driver).
static uint32_t      dma_buf[2][AUDIO_I2S_BUF_SAMPLES];
static int           dma_chan  = -1;
static volatile int  dma_play  = 0;   // index of the buffer currently in DMA
static audio_i2s_fill_cb_t fill_cb = NULL;

void audio_i2s_set_fill_cb(audio_i2s_fill_cb_t cb) {
    fill_cb = cb;
}

// ── DMA IRQ handler ──────────────────────────────────────────────────────────
// Registered on Core 0 so multicore_lockout (Flash writes) does not stop it.
// SRAM placement: Flash XIP is disabled during flash_range_program/erase.
static void __not_in_flash_func(audio_i2s_dma_irq)(void) {
    if (!dma_channel_get_irq0_status(dma_chan)) return;
    dma_channel_acknowledge_irq0(dma_chan);

    // Switch active buffer and immediately restart DMA to avoid any gap.
    dma_play ^= 1;
    dma_channel_set_read_addr(dma_chan, dma_buf[dma_play], false);
    dma_channel_set_trans_count(dma_chan, AUDIO_I2S_BUF_SAMPLES, true);

    // Fill the completed (idle) buffer for the next turn.
    int fill = 1 - dma_play;
    if (fill_cb) fill_cb(dma_buf[fill], AUDIO_I2S_BUF_SAMPLES);
}

// ── Public API ────────────────────────────────────────────────────────────────
void audio_i2s_init(void) {
    // Enable PA (power amplifier) before audio starts.
    gpio_init(PA_CTRL_PIN);
    gpio_set_dir(PA_CTRL_PIN, GPIO_OUT);
    gpio_put(PA_CTRL_PIN, 1);

    // ── MCLK PIO (pio1, SM0) ────────────────────────────────────────────────
    // Must start first so ES8311 can lock and begin generating BCLK/LRCLK.
    uint mclk_off = pio_add_program(MCLK_PIO, &mclk_pio_program);
    mclk_pio_program_init(MCLK_PIO, MCLK_PIO_SM, mclk_off, MCLK_PIN);
    float mclk_div = (float)clock_get_hz(clk_sys) / ((float)AUDIO_MCLK_HZ * 5.0f);
    pio_sm_set_clkdiv(MCLK_PIO, MCLK_PIO_SM, mclk_div);
    pio_sm_set_enabled(MCLK_PIO, MCLK_PIO_SM, true);

    // Give ES8311 time to lock its PLL to MCLK and start BCLK/LRCLK.
    sleep_ms(10);

    // ── I2S DOUT PIO (pio2, SM0) ─────────────────────────────────────────────
    // Pre-fill both buffers with silence.
    for (int i = 0; i < AUDIO_I2S_BUF_SAMPLES; i++) {
        dma_buf[0][i] = 0;
        dma_buf[1][i] = 0;
    }

    uint dout_off = pio_add_program(DOUT_PIO, &audio_pio_program);
    audio_pio_program_init(DOUT_PIO, DOUT_PIO_SM, dout_off, DOUT_PIN, LRCLK_PIN);
    pio_sm_set_clkdiv(DOUT_PIO, DOUT_PIO_SM, 1.0f);
    pio_sm_set_enabled(DOUT_PIO, DOUT_PIO_SM, true);

    // ── DMA channel ──────────────────────────────────────────────────────────
    dma_chan = dma_claim_unused_channel(true);
    dma_channel_config dc = dma_channel_get_default_config(dma_chan);
    channel_config_set_transfer_data_size(&dc, DMA_SIZE_32);
    channel_config_set_read_increment(&dc, true);
    channel_config_set_write_increment(&dc, false);
    // Pace DMA by PIO2 TX FIFO DREQ — one word consumed per LRCLK period.
    channel_config_set_dreq(&dc, pio_get_dreq(DOUT_PIO, DOUT_PIO_SM, true));

    dma_channel_configure(dma_chan, &dc,
        &DOUT_PIO->txf[DOUT_PIO_SM],   // write to PIO TX FIFO
        dma_buf[dma_play],
        AUDIO_I2S_BUF_SAMPLES,
        false);                          // don't start yet

    dma_channel_set_irq0_enabled(dma_chan, true);
    irq_set_exclusive_handler(DMA_IRQ_0, audio_i2s_dma_irq);
    irq_set_enabled(DMA_IRQ_0, true);

    // PIO instruction 0 consumes one sync word before entering the main loop.
    // The first word from DMA buffer 0 serves as this sync token and is
    // discarded by the PIO; the remaining words are audio.
    dma_channel_start(dma_chan);
}

void audio_i2s_stop(void) {
    if (dma_chan < 0) return;
    dma_channel_set_irq0_enabled(dma_chan, false);
    irq_set_enabled(DMA_IRQ_0, false);
    dma_channel_abort(dma_chan);
    pio_sm_set_enabled(DOUT_PIO, DOUT_PIO_SM, false);
    pio_sm_set_enabled(MCLK_PIO, MCLK_PIO_SM, false);
    gpio_put(PA_CTRL_PIN, 0); // silence the amplifier
}
